name: vigia_deputados
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <=3.1.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.0.20
  syncfusion_flutter_charts: ^23.1.36
  provider: ^6.0.5
  animations: ^2.0.8
  
  
  
  

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: inter-medium
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
    - family: inter-bold
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
