name: vigia_deputados
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.0.20
  syncfusion_flutter_charts: ^19.4.50
  glassmorphism: ^3.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: inter-medium
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
    - family: inter-bold
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
